-- Create analytics table
CREATE TABLE IF NOT EXISTS analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR NOT NULL,
    date DATE NOT NULL,
    count INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(type, date)
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_analytics_type_date ON analytics(type, date);

-- Create function to increment count
CREATE OR REPLACE FUNCTION increment_analytics_count()
RETURNS trigger AS $$
BEGIN
    IF (TG_OP = 'INSERT' AND EXISTS (
        SELECT 1 FROM analytics 
        WHERE type = NEW.type AND date = NEW.date
    )) THEN
        UPDATE analytics 
        SET count = count + 1 
        WHERE type = NEW.type AND date = NEW.date;
        RETURN NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for incrementing count
DROP TRIGGER IF EXISTS tr_increment_analytics_count ON analytics;
CREATE TRIGGER tr_increment_analytics_count
    BEFORE INSERT ON analytics
    FOR EACH ROW
    EXECUTE FUNCTION increment_analytics_count();
